###
GET http://localhost:9500/

###
GET http://localhost:9500/api/users/all

###
POST http://localhost:9500/api/users/register
Content-Type: application/json

{
    "username": "Emmanuel Kipsang",
    "email": "emmanuel@gmail.com",
    "password": "@Emmanuel123"

}

###
POST http://localhost:9500/api/users/auth/login
Content-Type: application/json

{
    "username": "Emmanuel Kipsang",
    "password": "@Emmanuel123"
}

