
// USERS ENDPOINTS

###
GET http://localhost:9500/

###
GET http://localhost:9500/api/users/all

###
POST http://localhost:9500/api/users/register
Content-Type: application/json

{
    "username": "Abel  Kipsang",
    "email": "abel@gmail.com",
    "password": "@Abel123"

}

###
POST http://localhost:9500/api/users/auth/login
Content-Type: application/json

{
    "username": "Emmanuel Kipsang",
    "password": "@Emmanuel123"
}

###
DELETE http://localhost:9500/api/users/7e1eb6fe-80d0-4017-b594-5eb4bf644376
