
// USERS ENDPOINTS

###
GET http://localhost:9500/

###

GET http://localhost:9500/api/users/all

###
GET http://localhost:9500/api/users/e104137f-6098-45f0-a1ed-3562ff1d14f6

###
POST http://localhost:9500/api/users/register
Content-Type: application/json

{
    "Username": "Abel Kipsang",
    "Email": "abel@gmail.com",
    "Password": "@Abel123",
    "TagName": "mkuru",
    "Location": "Nyeri"
}


###
POST http://localhost:9500/api/users/auth/login
Content-Type: application/json

{
    "username": "Abel Kipsang",
    "password": "@Abel123"
}

###
DELETE http://localhost:9500/api/users/e95ef228-da59-4437-a549-1593dcfee095


###
PUT http://localhost:9500/api/users/e104137f-6098-45f0-a1ed-3562ff1d14f6

{
    "username": "Abel  Mutua",
    "email": "mutua@gmail.com",
    "password": "@Mutua123"

}



//POST ENDPOINTS


